### ISSUE TITLE
slurmctld fails to start: invalid plugin select/cons_res

### ISSUE THREAD

**Issue by liffiton** [XSEDE/CRI_Jetstream_Cluster#19]
I'm trying to launch a virtual cluster in a Rocky 8 instance on Jetstream2 following the documentation [here](https://docs.jetstream-cloud.org/ui/exo/push-button-cluster/).

On the instance I create, `slurmctld` fails to start, giving an error in the logs: `fatal: Can't find plugin for select/cons_res`.  `slurmctld --version` prints `slurm 23.11.4`.

In the [`slurm.conf` documentation](https://slurm.schedmd.com/slurm.conf.html), it looks like `cons_res` is "legacy" and no longer an accepted value for the `SelectType` setting in `slurm.conf`.

If I change `select/cons_res` to the allowed `select/cons_tres` value in `slurm.conf`, then `slurmctld` starts successfully.

**Comment by julianpistorius** [comment]
Fixed by #21
