### ISSUE TITLE
Compute node setup fails in Rocky 8 due to newer ansible

### ISSUE THREAD

**Issue by liffiton** [XSEDE/CRI_Jetstream_Cluster#20]
Creating a new cluster on Rocky 8 fails with an error when using ansible to set up the compute node.  Specifically, it hits the "future feature annotations is not defined" error discussed in [Newer versions of Ansible don't work with RHEL 8](https://www.jeffgeerling.com/blog/2024/newer-versions-ansible-dont-work-rhel-8).

As mentioned in the post, installing a slightly older version of `ansible-core` on the head node allows it work:

```
pip install "ansible-core<2.17"
```

**Comment by julianpistorius** [comment]
Fixed by #21
