### ISSUE TITLE
Problem: `cluster_create_local.sh` breaks on CentOS 8

### ISSUE THREAD

**Issue by julianpistorius** [XSEDE/CRI_Jetstream_Cluster#7]
This just started happening:

```
==> /var/log/cloud-init-output.log <==
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
2022-02-03 17:32:00,162 - util.py[WARNING]: Package upgrade failed
CentOS Linux 8 - AppStream                      169  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
2022-02-03 17:32:01,164 - util.py[WARNING]: Failed to install packages: ['python3-virtualenv', 'git']
2022-02-03 17:32:01,165 - cc_package_update_upgrade_install.py[WARNING]: 3 failed with exceptions, re-raising the last one
2022-02-03 17:32:01,169 - util.py[WARNING]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3.6/site-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) failed
Cloning into 'CRI_Jetstream_Cluster'...
CentOS Linux 8 - AppStream                      133  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
CentOS Linux 8 - AppStream                      116  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

Searching for the error led me to this:

https://forums.centos.org/viewtopic.php?f=54&t=78708

> CentOS 8 went EOL at the end of December and in line with all the public announcements, the content of the CentOS 8 repos has been moved to [vault.centos.org](http://vault.centos.org/). It's time to move to something else.

Jetstream2 will be switching to Rocky and will not have CentOS 8.

We should test the cluster creation scripts (both `cluster_create_local.sh` and `cluster_create.sh` with Rocky 8 on Jetstream, and make any chances necessary.

**Comment by julianpistorius** [comment]
Related Exosphere issue: https://gitlab.com/exosphere/exosphere/-/issues/672

**Comment by julianpistorius** [comment]
Any further news @DImuthuUpe? Let me know if I can help.

**Comment by DImuthuUpe** [comment]
@julianpistorius I am going to finish this over the weekend. Sorry I just got busy with PEARC deadlines

**Comment by julianpistorius** [comment]
Hi @DImuthuUpe. Exosphere now uses the `rocky-linux` branch. You can see the changes here:

https://gitlab.com/exosphere/exosphere/-/merge_requests/613

Once/if you merge `rocky-linux` into `main` I'll change the code in Exosphere to use `main` as well.

I also have a PR to update the J2 documentation to reflect the above changes:

https://github.com/jetstream-cloud/js2docs/pull/11

Thanks again for your help getting this to work on Rocky!

**Comment by DImuthuUpe** [comment]
Happy to help @julianpistorius :). Is it ok if I close this?

**Comment by julianpistorius** [comment]
Thank you @DImuthuUpe. I'll close it.
